const { test, expect } = require('@playwright/test');
const { mkdir, readFile } = require('node:fs/promises');
const data = require('../outputs/maps/assets/facilities.json').facilities;
const mapPath = '/outputs/maps/datacentermap_sweden_interactive_map.html';
const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aP2kAAAAASUVORK5CYII=', 'base64');
test.beforeEach(async ({ page }) => {
 for(const host of ['tile.openstreetmap.org','server.arcgisonline.com']) await page.route('https://'+host+'/**',route=>route.fulfill({contentType:'image/png',body:png}));
});
test('desktop: filters, keyboard selection, source link, area counts, satellite and CSV', async ({ page }) => {
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.setViewportSize({width:1500,height:1100});
 await page.goto(mapPath);
 await expect(page.locator('#result-count')).toHaveText('114 av 114 anläggningar');
 await expect(page.locator('#stat-operators')).toHaveText('50');
 expect(await page.evaluate(()=>DatacenterMap.cluster.getLayers().length)).toBe(114);
 await page.getByLabel('Operatör',{exact:true}).selectOption('Microsoft');
 await expect(page.locator('#result-count')).toHaveText('18 av 114 anläggningar');
 await page.getByRole('button',{name:'Antal per län',exact:false}).click();
 expect(await page.evaluate(()=>Object.values(DatacenterMap.counts.counties).reduce((a,b)=>a+b,0))).toBe(18);
 expect(await page.evaluate(()=>DatacenterMap.mode)).toBe('counties');
 await expect(page.locator('#legend')).toContainText('Summeringen följer');
 await page.getByRole('button',{name:'Rensa filter',exact:true}).click();
 await page.getByLabel('Län',{exact:true}).selectOption('01');
 await expect(page.locator('#result-count')).toHaveText('49 av 114 anläggningar');
 expect(await page.evaluate(()=>DatacenterMap.counts.counties['01'])).toBe(49);
 await page.getByRole('button',{name:'Antal per kommun',exact:false}).click();
 expect(await page.evaluate(()=>Object.values(DatacenterMap.counts.municipalities).reduce((a,b)=>a+b,0))).toBe(49);
 await page.evaluate(()=>DatacenterMap.areaLayers.municipalities.getLayers().find(l=>l.feature.properties.code==='0180').fire('click'));
 await expect(page.locator('#detail h2')).toHaveText('Stockholm');
 await page.getByRole('button',{name:'Visa områdets anläggningar'}).click();
 const stockholm = data.filter(p=>p.kommun==='0180').length;
 await expect(page.locator('#result-count')).toHaveText(stockholm+' av 114 anläggningar');
 await page.getByRole('button',{name:'Rensa filter',exact:true}).click();
 await page.getByLabel('Status',{exact:true}).selectOption('planned');
 await expect(page.locator('#result-count')).toHaveText('9 av 114 anläggningar');
 await page.getByLabel('Typ',{exact:true}).selectOption('Hyperscaler');
 await expect(page.locator('#result-count')).toHaveText(data.filter(p=>p.stage==='planned'&&p.type==='Hyperscaler').length+' av 114 anläggningar');
 await page.getByRole('button',{name:'Rensa filter',exact:true}).click();
 const selected=data.find(p=>p.name==='Esbogatan 11 (STO1)');
 await page.getByRole('searchbox').fill(selected.name);
 await expect(page.locator('#result-count')).toHaveText('1 av 114 anläggningar');
 await page.getByRole('searchbox').press('Enter');
 await expect(page.locator('#detail h2')).toHaveText(selected.name);
 await expect(page.locator('#detail h2')).toBeFocused();
 await expect(page.locator('.facility-source')).toHaveAttribute('href',selected.url);
 const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button',{name:/Hämta urval/}).click()]);
 const stream = await download.createReadStream();const chunks=[];for await(const chunk of stream)chunks.push(chunk);
 const csv=Buffer.concat(chunks).toString('utf8');
 expect(csv).toContain(selected.name);expect(csv.split('\r\n')).toHaveLength(2);
 await page.getByLabel('Bakgrund',{exact:true}).selectOption('satellite');
 expect(await page.evaluate(()=>document.querySelector('.map-panel').classList.contains('satellite'))).toBe(true);
 await page.getByLabel('Bakgrund',{exact:true}).selectOption('osm');
 await page.getByRole('button',{name:/Om underlaget/}).click();
 await expect(page.getByRole('dialog')).toContainText('Insamlingsdatum är inte dokumenterat');
 await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'Rensa filter',exact:true}).click();
 await page.getByRole('searchbox').fill('inget-matchande-datacenter');
 await expect(page.locator('#result-count')).toHaveText('0 av 114 anläggningar');
 await expect(page.locator('#download')).toBeDisabled();
 await page.getByRole('button',{name:'Rensa filter',exact:true}).click();
 await mkdir('.artifacts',{recursive:true});
 await page.screenshot({path:'.artifacts/datacenter-desktop.png',fullPage:true});
 expect(errors).toEqual([]);
});
test('mobile: selection, map resize and usable layout at 320–1024 pixels', async ({ page }) => {
 await page.setViewportSize({width:390,height:844});await page.goto(mapPath);
 await expect(page.locator('#result-count')).toHaveText('114 av 114 anläggningar');
 await page.getByRole('searchbox').fill('Esbogatan 11 (STO1)');
 await page.getByRole('searchbox').press('Enter');
 await expect(page.locator('#detail h2')).toHaveText('Esbogatan 11 (STO1)');
 await page.getByRole('button',{name:'Rensa filter',exact:true}).click();
 for(const width of [320,390,768,1024]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'overflow at '+width).toBe(true);}
 await page.setViewportSize({width:390,height:844});
 await page.getByRole('button',{name:'Visa urval ⤢',exact:true}).click();
 await page.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));
 await page.screenshot({path:'.artifacts/datacenter-mobile.png',fullPage:true});
});